name: hourglass-server
services:
  db:
    container_name: "hourglass-db-postgres"
    image: postgres:16.3
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=start-postgres
    ports:
      - 5432:5432
volumes:
  db_data:
    name: hourglass-db-data